config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lists#index"
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
  validates :detail, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_tlist, only: [:show, :edit, :update]


  def index
    @lists = List.includes(:user)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :detail, :image).merge(user_id: current_user.id)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WishList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "Wish List", root_path, class: :logo %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New List", new_list_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: list, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <%# <div class="field">
    <%= f.label :hoge, "キャッチコピー" %><br />
    <%# <%= f.text_area :hoge, class: :form__text, id:"prototype_catch_copy" %>
  <%# </div> %> 

  <div class="field">
    <%= f.label :detail, "詳細" %><br />
    <%= f.text_area :detail, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="card">
  <%= link_to image_tag(list.image, class: :card__img ), list_path(list) %>
  <div class="card__body">
    <%= link_to list.title, list_path(list), class: :card__title%>
    <p class="card__summary">
      <%= list.detail %>
    </p>
    <%# <%= link_to "by #{list.user.nickname}", user_path(list.user), class: :card__user %> 
  </div>
</div>

app/views/lists/_lists.html.erb
<div class="card">
  <%= link_to image_tag("画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "タイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "詳細" %>
    </p>
    <%= link_to "by #{current_user.nickname}", root_path, class: :card__user %>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { list: @list } %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<main class="main">
  <div class="inner">
  <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.nickname}さん", user_path(list.user), class: :greeting__link %>
      </div>
  <% end %>
    <div class="card__wrapper">
    <%= render partial: 'list', collection: @lists %>
    </div>
  </div>
</main>

app/views/lists/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">目標・やりたいこと</h2>
      <%= render partial: "form", locals: { list: @list } %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<main class="main">
  <div class="inner">
    <div class="list__wrapper">
      <p class="list__hedding">
        <%= @list.title%>
      </p>
      <%= link_to "by #{current_user.nickname}", user_path(@list.user), class: :list__user %>
      <% if user_signed_in? && current_user.id == @list.user_id %>
        <div class="list__manage">
          <%= link_to "編集する", edit_list_path(@list), class: :list__btn %>
          <%= link_to "削除する", list_path(@list), class: :list__btn %>
        </div>
      <% end %>
      <div class="list__image">
        <%= image_tag @list.image %>
      </div>
      <%# <div class="list__body">
        <div class="list__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= "プロトタイプのキャッチコピー" %>
          <%# </p>
        </div> %>
        <div class="list__detail">
          <p class="detail__title">詳細</p>
          <p class="detail__message">
            <%= @list.detail %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# <% if user_signed_in? %>
            <%# <%= form_with model: list,local: true do |f|%>
            <%# <div class="field">
              <%= f.label :hoge, "コメント" %><br />
              <%# <%= f.text_field :hoge, id:"comment_content" %>
            <%# </div> %>
            <%# <div class="actions"> %>
              <%# <%= f.submit "送信する", class: :form__btn  %> %>
            <%# </div> %>
            <%# <% end %> 
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <%# <%= " コメントのテキスト "%>
              <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <%# <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "ユーザーのプロフィール" %></td>
          <%# </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= "ユーザーの所属" %></td>
          <%# </tr> %>
          <%# <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= "ユーザーの役職" %></td>
          <%# </tr>  %> 
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのList"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'lists/list', collection: @user.list %>
      </div>
    </div>
  </div>
</div>